Repository Floating-Dartists/matomo-tracker, pull requests merged in 2022-09, with the labels that each got.

#17 Feature: Add dimensions tracking
  README.md
  lib/src/matomo.dart
  lib/src/matomo_event.dart
Labels: enhancement

#19 [#18] - Initialize SharedPreferences before calling getString
  lib/src/matomo.dart
Labels: bug

#20 Release 1.4.1
  CHANGELOG.md
  pubspec.yaml
Labels: release

#21 Feature/dimensions tracking update
  README.md
  lib/src/matomo.dart
Labels: documentation, enhancement, needs verification

#23 Release 1.5.0
  CHANGELOG.md
  README.md
  analysis_options.yaml
  lib/matomo_tracker.dart
  lib/src/traceable_widget.dart
  lib/src/traceable_widget_mixin.dart
  pubspec.yaml
Labels: release

#24 Prepare v1.6.0
  CHANGELOG.md
  example/pubspec.yaml
  lib/src/logger.dart
  lib/src/matomo.dart
  lib/src/platform_info/platform_info.dart
  lib/src/platform_info/platform_info_interface.dart
  lib/src/platform_info/platform_info_io.dart
  lib/src/platform_info/platform_info_web.dart
  pubspec.yaml
Labels: enhancement, release
