Repository Floating-Dartists/matomo-tracker, pull requests merged in 2023-05, with the labels that each got.

#59 Support for custom http headers
  CHANGELOG.md
  README.md
  example/lib/main.dart
  lib/matomo_tracker.dart
  lib/src/logger.dart
  lib/src/logger/log_record.dart
  lib/src/logger/logger.dart
  lib/src/matomo.dart
  lib/src/matomo_dispatcher.dart
  pubspec.yaml
  test/src/logger/log_record_test.dart
  test/src/logger/logger_test.dart
  test/src/matomo_dispatcher_test.dart
Labels: enhancement

#63 Documentation
  README.md
  lib/src/matomo.dart
  lib/src/traceable_widget_mixin.dart
  lib/src/visitor.dart
Labels: documentation

#68 Refactor/#65 update parameters
  CHANGELOG.md
  README.md
  example/lib/main.dart
  lib/matomo_tracker.dart
  lib/src/assert.dart
  lib/src/event_info.dart
  lib/src/matomo.dart
  lib/src/matomo_event.dart
  lib/src/traceable_widget.dart
  lib/src/traceable_widget_mixin.dart
  lib/src/visitor.dart
  pubspec.yaml
  test/ressources/mock/data.dart
  test/ressources/utils/get_initialized_mamoto_tracker.dart
  test/src/assert_test.dart
  test/src/event_info_test.dart
  test/src/matomo_event_test.dart
  test/src/matomo_test.dart
  test/src/traceable_widget_mixin_test.dart
  test/src/traceable_widget_test.dart
  test/src/visitor_test.dart
Labels: enhancement

#73 Added RouteAware implementation
  README.md
  example/lib/main.dart
  example/pubspec.yaml
  lib/src/matomo.dart
  lib/src/matomo_event.dart
  lib/src/traceable_widget_mixin.dart
  test/ressources/utils/testable_app.dart
  test/src/traceable_widget_mixin_test.dart
  test/src/traceable_widget_test.dart
Labels: enhancement

#86 Content tracking and ca issue
  example/lib/main.dart
  lib/matomo_tracker.dart
  lib/src/content.dart
  lib/src/matomo.dart
  lib/src/matomo_event.dart
  test/ressources/mock/data.dart
  test/src/content_test.dart
  test/src/matomo_event_test.dart
  test/src/matomo_test.dart
Labels: enhancement

#99 Fix/#99 update http dependency
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: dependencies

#100 Updated LICENCE to account for matomo_tracker contributors
  LICENSE
Labels: documentation

#101 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#97 Persistent Dispatch Queue
  README.md
  example/lib/main.dart
  lib/matomo_tracker.dart
  lib/src/dispatch_settings.dart
  lib/src/local_storage/cookieless_storage.dart
  lib/src/local_storage/local_storage.dart
  lib/src/local_storage/shared_prefs_storage.dart
  lib/src/matomo.dart
  lib/src/persistent_queue.dart
  pubspec.yaml
  test/src/dispatch_settings_test.dart
  test/src/local_storage/shared_prefs_storage_test.dart
  test/src/persistent_queue_test.dart
Labels: enhancement
